

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: MTART
Empirical Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAMTARTF -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GF -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTART 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.286497
Subtree Equality Vectors for gap columns full tree traversal time: 1.361698
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTART/RAxML_binaryModelParameters.GF


Overall Time for Tree Evaluation 39.080433
Final GAMMA  likelihood: -41028.494600


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.710726
Tree-Length: 265.958350
rate A <-> R: 0.001078
rate A <-> N : 0.001078
rate A <-> D: 0.005391
rate A <-> C: 1.369272
rate A <-> Q: 0.001078
rate A <-> E: 0.001078
rate A <-> G: 1.078167
rate A <-> H: 0.001078
rate A <-> I: 0.140162
rate A <-> L: 0.021563
rate A <-> K: 0.001078
rate A <-> M: 0.652291
rate A <-> F: 0.070081
rate A <-> P: 0.264151
rate A <-> S: 3.628032
rate A <-> T: 1.315364
rate A <-> W: 0.001078
rate A <-> Y: 0.005391
rate A <-> V: 1.832884
rate R <-> N : 0.001078
rate R <-> D: 0.021563
rate R <-> C: 0.194070
rate R <-> Q: 0.830189
rate R <-> E: 0.001078
rate R <-> G: 0.001078
rate R <-> H: 0.221024
rate R <-> I: 0.010782
rate R <-> L: 0.010782
rate R <-> K: 1.126685
rate R <-> M: 0.026954
rate R <-> F: 0.026954
rate R <-> P: 0.001078
rate R <-> S: 0.016173
rate R <-> T: 0.001078
rate R <-> W: 0.001078
rate R <-> Y: 0.021563
rate R <-> V: 0.001078
rate N  <-> D: 2.695418
rate N  <-> C: 0.528302
rate N  <-> Q: 1.412399
rate N  <-> E: 0.986523
rate N  <-> G: 0.652291
rate N  <-> H: 0.970350
rate N  <-> I: 0.113208
rate N  <-> L: 0.070081
rate N  <-> K: 2.517520
rate N  <-> M: 0.425876
rate N  <-> F: 0.107817
rate N  <-> P: 0.091644
rate N  <-> S: 2.145553
rate N  <-> T: 0.894879
rate N  <-> W: 0.043127
rate N  <-> Y: 1.353100
rate N  <-> V: 0.123989
rate D <-> C: 0.059299
rate D <-> Q: 0.001078
rate D <-> E: 4.646900
rate D <-> G: 0.064690
rate D <-> H: 0.001078
rate D <-> I: 0.037736
rate D <-> L: 0.005391
rate D <-> K: 0.010782
rate D <-> M: 0.001078
rate D <-> F: 0.001078
rate D <-> P: 0.001078
rate D <-> S: 0.237197
rate D <-> T: 0.001078
rate D <-> W: 0.001078
rate D <-> Y: 0.001078
rate D <-> V: 0.001078
rate C <-> Q: 0.001078
rate C <-> E: 0.001078
rate C <-> G: 0.436658
rate C <-> H: 0.064690
rate C <-> I: 0.339623
rate C <-> L: 0.425876
rate C <-> K: 0.001078
rate C <-> M: 1.681941
rate C <-> F: 0.991914
rate C <-> P: 0.001078
rate C <-> S: 3.579515
rate C <-> T: 0.986523
rate C <-> W: 0.118598
rate C <-> Y: 0.388140
rate C <-> V: 1.886792
rate Q <-> E: 1.412399
rate Q <-> G: 0.016173
rate Q <-> H: 1.692722
rate Q <-> I: 0.059299
rate Q <-> L: 0.086253
rate Q <-> K: 1.881402
rate Q <-> M: 0.361186
rate Q <-> F: 0.001078
rate Q <-> P: 0.210243
rate Q <-> S: 0.280323
rate Q <-> T: 0.237197
rate Q <-> W: 0.037736
rate Q <-> Y: 0.469003
rate Q <-> V: 0.001078
rate E <-> G: 0.237197
rate E <-> H: 0.080863
rate E <-> I: 0.037736
rate E <-> L: 0.010782
rate E <-> K: 0.571429
rate E <-> M: 0.001078
rate E <-> F: 0.001078
rate E <-> P: 0.043127
rate E <-> S: 0.167116
rate E <-> T: 0.231806
rate E <-> W: 0.059299
rate E <-> Y: 0.043127
rate E <-> V: 0.075472
rate G <-> H: 0.001078
rate G <-> I: 0.016173
rate G <-> L: 0.005391
rate G <-> K: 0.001078
rate G <-> M: 0.301887
rate G <-> F: 0.005391
rate G <-> P: 0.001078
rate G <-> S: 1.218329
rate G <-> T: 0.001078
rate G <-> W: 0.010782
rate G <-> Y: 0.048518
rate G <-> V: 0.016173
rate H <-> I: 0.001078
rate H <-> L: 0.032345
rate H <-> K: 0.001078
rate H <-> M: 0.001078
rate H <-> F: 0.075472
rate H <-> P: 0.005391
rate H <-> S: 0.059299
rate H <-> T: 0.102426
rate H <-> W: 0.001078
rate H <-> Y: 1.029650
rate H <-> V: 0.001078
rate I <-> L: 2.776280
rate I <-> K: 0.016173
rate I <-> M: 2.776280
rate I <-> F: 0.636119
rate I <-> P: 0.001078
rate I <-> S: 0.037736
rate I <-> T: 1.099730
rate I <-> W: 0.001078
rate I <-> Y: 0.064690
rate I <-> V: 10.000000
rate L <-> K: 0.021563
rate L <-> M: 4.770889
rate L <-> F: 1.417790
rate L <-> P: 0.064690
rate L <-> S: 0.043127
rate L <-> T: 0.258760
rate L <-> W: 0.113208
rate L <-> Y: 0.107817
rate L <-> V: 0.458221
rate K <-> M: 0.571429
rate K <-> F: 0.059299
rate K <-> P: 0.091644
rate K <-> S: 0.776280
rate K <-> T: 0.377358
rate K <-> W: 0.086253
rate K <-> Y: 0.630728
rate K <-> V: 0.140162
rate M <-> F: 1.735849
rate M <-> P: 0.026954
rate M <-> S: 0.603774
rate M <-> T: 1.557951
rate M <-> W: 0.382749
rate M <-> Y: 0.382749
rate M <-> V: 1.514825
rate F <-> P: 0.080863
rate F <-> S: 0.194070
rate F <-> T: 0.075472
rate F <-> W: 0.291105
rate F <-> Y: 4.269542
rate F <-> V: 0.280323
rate P <-> S: 0.469003
rate P <-> T: 0.253369
rate P <-> W: 0.001078
rate P <-> Y: 0.097035
rate P <-> V: 0.172507
rate S <-> T: 3.557951
rate S <-> W: 0.010782
rate S <-> Y: 0.161725
rate S <-> V: 0.328841
rate T <-> W: 0.001078
rate T <-> Y: 0.247978
rate T <-> V: 2.932615
rate W <-> Y: 0.204852
rate W <-> V: 0.001078
rate Y <-> V: 0.010782

freq pi(A): 0.054853
freq pi(R): 0.046897
freq pi(N ): 0.032881
freq pi(D): 0.049507
freq pi(C): 0.131460
freq pi(Q): 0.034963
freq pi(E): 0.060758
freq pi(G): 0.071417
freq pi(H): 0.049166
freq pi(I): 0.037791
freq pi(L): 0.063710
freq pi(K): 0.070547
freq pi(M): 0.015135
freq pi(F): 0.055008
freq pi(P): 0.033005
freq pi(S): 0.045281
freq pi(T): 0.038599
freq pi(W): 0.011561
freq pi(Y): 0.046804
freq pi(V): 0.050657

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTART/RAxML_result.GF
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTART/RAxML_log.GF
