

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: MTZOA
Fixed Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAMTZOA -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n G -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTZOA 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.219144
Subtree Equality Vectors for gap columns full tree traversal time: 1.296536
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTZOA/RAxML_binaryModelParameters.G


Overall Time for Tree Evaluation 44.031701
Final GAMMA  likelihood: -40722.985301


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.486220
Tree-Length: 272.399861
rate A <-> R: 0.019291
rate A <-> N : 0.009938
rate A <-> D: 0.094119
rate A <-> C: 1.593008
rate A <-> Q: 0.042675
rate A <-> E: 0.099965
rate A <-> G: 1.691219
rate A <-> H: 0.013446
rate A <-> I: 0.194084
rate A <-> L: 0.091196
rate A <-> K: 0.001169
rate A <-> M: 0.797966
rate A <-> F: 0.154916
rate A <-> P: 0.361277
rate A <-> S: 3.770022
rate A <-> T: 2.210336
rate A <-> W: 0.018122
rate A <-> Y: 0.012276
rate A <-> V: 1.881796
rate R <-> N : 0.196422
rate R <-> D: 0.018707
rate R <-> C: 0.357185
rate R <-> Q: 1.350403
rate R <-> E: 0.037414
rate R <-> G: 0.042090
rate R <-> H: 0.360692
rate R <-> I: 0.001169
rate R <-> L: 0.023968
rate R <-> K: 1.708757
rate R <-> M: 0.022214
rate R <-> F: 0.001169
rate R <-> P: 0.043844
rate R <-> S: 0.068982
rate R <-> T: 0.018707
rate R <-> W: 0.098796
rate R <-> Y: 0.080673
rate R <-> V: 0.029814
rate N  <-> D: 3.606922
rate N  <-> C: 0.553022
rate N  <-> Q: 1.112475
rate N  <-> E: 1.017187
rate N  <-> G: 0.580498
rate N  <-> H: 1.338127
rate N  <-> I: 0.142055
rate N  <-> L: 0.046183
rate N  <-> K: 2.416696
rate N  <-> M: 0.430843
rate N  <-> F: 0.075412
rate N  <-> P: 0.132117
rate N  <-> S: 2.456448
rate N  <-> T: 1.079154
rate N  <-> W: 0.037414
rate N  <-> Y: 0.827780
rate N  <-> V: 0.041506
rate D <-> C: 0.055536
rate D <-> Q: 0.112826
rate D <-> E: 5.165439
rate D <-> G: 0.151993
rate D <-> H: 0.325032
rate D <-> I: 0.008769
rate D <-> L: 0.002923
rate D <-> K: 0.001169
rate D <-> M: 0.001169
rate D <-> F: 0.011692
rate D <-> P: 0.001169
rate D <-> S: 0.300479
rate D <-> T: 0.013446
rate D <-> W: 0.001169
rate D <-> Y: 0.081258
rate D <-> V: 0.021630
rate C <-> Q: 0.287034
rate C <-> E: 0.019876
rate C <-> G: 0.481702
rate C <-> H: 0.219221
rate C <-> I: 0.285280
rate C <-> L: 0.349000
rate C <-> K: 0.001169
rate C <-> M: 1.547995
rate C <-> F: 0.980942
rate C <-> P: 0.047352
rate C <-> S: 3.836665
rate C <-> T: 1.163335
rate C <-> W: 0.211037
rate C <-> Y: 0.448381
rate C <-> V: 1.425231
rate Q <-> E: 2.042558
rate Q <-> G: 0.052029
rate Q <-> H: 2.465801
rate Q <-> I: 0.001169
rate Q <-> L: 0.134456
rate Q <-> K: 1.952531
rate Q <-> M: 0.490471
rate Q <-> F: 0.055536
rate Q <-> P: 0.305156
rate Q <-> S: 0.563545
rate Q <-> T: 0.230329
rate Q <-> W: 0.035660
rate Q <-> Y: 0.305741
rate Q <-> V: 0.052613
rate E <-> G: 0.251958
rate E <-> H: 0.087104
rate E <-> I: 0.042675
rate E <-> L: 0.005846
rate E <-> K: 0.954051
rate E <-> M: 0.001169
rate E <-> F: 0.001169
rate E <-> P: 0.120426
rate E <-> S: 0.224483
rate E <-> T: 0.201684
rate E <-> W: 0.020461
rate E <-> Y: 0.058459
rate E <-> V: 0.095288
rate G <-> H: 0.043260
rate G <-> I: 0.019876
rate G <-> L: 0.020461
rate G <-> K: 0.059044
rate G <-> M: 0.305156
rate G <-> F: 0.033906
rate G <-> P: 0.007600
rate G <-> S: 1.502981
rate G <-> T: 0.030399
rate G <-> W: 0.071905
rate G <-> Y: 0.025137
rate G <-> V: 0.138548
rate H <-> I: 0.009353
rate H <-> L: 0.038583
rate H <-> K: 0.139717
rate H <-> M: 0.041506
rate H <-> F: 0.076581
rate H <-> P: 0.091196
rate H <-> S: 0.135040
rate H <-> T: 0.113410
rate H <-> W: 0.026307
rate H <-> Y: 1.557933
rate H <-> V: 0.001754
rate I <-> L: 2.485678
rate I <-> K: 0.049106
rate I <-> M: 2.628902
rate I <-> F: 0.527885
rate I <-> P: 0.015199
rate I <-> S: 0.042090
rate I <-> T: 1.299544
rate I <-> W: 0.056705
rate I <-> Y: 0.076581
rate I <-> V: 10.000000
rate L <-> K: 0.039168
rate L <-> M: 3.719747
rate L <-> F: 1.369110
rate L <-> P: 0.066643
rate L <-> S: 0.088858
rate L <-> T: 0.292295
rate L <-> W: 0.159009
rate L <-> Y: 0.033322
rate L <-> V: 0.737168
rate K <-> M: 0.485210
rate K <-> F: 0.095288
rate K <-> P: 0.142055
rate K <-> S: 0.847071
rate K <-> T: 0.441366
rate K <-> W: 0.038583
rate K <-> Y: 0.263066
rate K <-> V: 0.064890
rate M <-> F: 1.260376
rate M <-> P: 0.031568
rate M <-> S: 0.557114
rate M <-> T: 1.783585
rate M <-> W: 0.284695
rate M <-> Y: 0.242020
rate M <-> V: 1.634514
rate F <-> P: 0.061382
rate F <-> S: 0.188238
rate F <-> T: 0.112826
rate F <-> W: 0.340231
rate F <-> Y: 3.452005
rate F <-> V: 0.348416
rate P <-> S: 0.465918
rate P <-> T: 0.332632
rate P <-> W: 0.007600
rate P <-> Y: 0.024553
rate P <-> V: 0.104642
rate S <-> T: 3.895125
rate S <-> W: 0.060213
rate S <-> Y: 0.173623
rate S <-> V: 0.289372
rate T <-> W: 0.021045
rate T <-> Y: 0.169531
rate T <-> V: 2.317316
rate W <-> Y: 0.466503
rate W <-> V: 0.080089
rate Y <-> V: 0.091196

freq pi(A): 0.069000
freq pi(R): 0.021000
freq pi(N ): 0.030000
freq pi(D): 0.020000
freq pi(C): 0.010000
freq pi(Q): 0.019000
freq pi(E): 0.025000
freq pi(G): 0.072000
freq pi(H): 0.027000
freq pi(I): 0.085000
freq pi(L): 0.157000
freq pi(K): 0.019000
freq pi(M): 0.051000
freq pi(F): 0.082000
freq pi(P): 0.045000
freq pi(S): 0.081000
freq pi(T): 0.056000
freq pi(W): 0.028000
freq pi(Y): 0.037000
freq pi(V): 0.066000

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTZOA/RAxML_result.G
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTZOA/RAxML_log.G
