

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: JTTDCMUT
Empirical Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAJTTDCMUTF -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GF -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTTDCMUT 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.287535
Subtree Equality Vectors for gap columns full tree traversal time: 1.352960
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTTDCMUT/RAxML_binaryModelParameters.GF


Overall Time for Tree Evaluation 43.476188
Final GAMMA  likelihood: -39130.455573


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.751307
Tree-Length: 146.129563
rate A <-> R: 0.557669
rate A <-> N : 0.585243
rate A <-> D: 0.867894
rate A <-> C: 0.602561
rate A <-> Q: 0.583940
rate A <-> E: 1.118825
rate A <-> G: 1.825225
rate A <-> H: 0.230723
rate A <-> I: 0.379365
rate A <-> L: 0.325161
rate A <-> K: 0.387497
rate A <-> M: 0.492341
rate A <-> F: 0.145053
rate A <-> P: 2.055392
rate A <-> S: 4.077112
rate A <-> T: 4.806579
rate A <-> W: 0.088451
rate A <-> Y: 0.146311
rate A <-> V: 3.067106
rate R <-> N : 0.473146
rate R <-> D: 0.162471
rate R <-> C: 1.069697
rate R <-> Q: 3.169722
rate R <-> E: 0.334052
rate R <-> G: 1.426117
rate R <-> H: 3.367621
rate R <-> I: 0.250888
rate R <-> L: 0.390459
rate R <-> K: 6.848431
rate R <-> M: 0.452116
rate R <-> F: 0.068507
rate R <-> P: 0.745221
rate R <-> S: 1.050511
rate R <-> T: 0.682070
rate R <-> W: 1.319455
rate R <-> Y: 0.247118
rate R <-> V: 0.180403
rate N  <-> D: 5.820813
rate N  <-> C: 0.328627
rate N  <-> Q: 0.806418
rate N  <-> E: 0.606376
rate N  <-> G: 0.811116
rate N  <-> H: 4.222574
rate N  <-> I: 0.515005
rate N  <-> L: 0.144000
rate N  <-> K: 2.653170
rate N  <-> M: 0.346887
rate N  <-> F: 0.077073
rate N  <-> P: 0.127758
rate N  <-> S: 5.305217
rate N  <-> T: 2.466252
rate N  <-> W: 0.029054
rate N  <-> Y: 0.734946
rate N  <-> V: 0.172568
rate D <-> C: 0.110788
rate D <-> Q: 0.547146
rate D <-> E: 8.146217
rate D <-> G: 1.334636
rate D <-> H: 1.082807
rate D <-> I: 0.121637
rate D <-> L: 0.064492
rate D <-> K: 0.296274
rate D <-> M: 0.199289
rate D <-> F: 0.034112
rate D <-> P: 0.133380
rate D <-> S: 0.618074
rate D <-> T: 0.445942
rate D <-> W: 0.060275
rate D <-> Y: 0.476143
rate D <-> V: 0.330672
rate C <-> Q: 0.095767
rate C <-> E: 0.056542
rate C <-> G: 0.573099
rate C <-> H: 0.760439
rate C <-> I: 0.157919
rate C <-> L: 0.172639
rate C <-> K: 0.051405
rate C <-> M: 0.429205
rate C <-> F: 0.711495
rate C <-> P: 0.129698
rate C <-> S: 2.260692
rate C <-> T: 0.492790
rate C <-> W: 1.158158
rate C <-> Y: 2.218234
rate C <-> V: 0.651696
rate Q <-> E: 3.584777
rate Q <-> G: 0.242601
rate Q <-> H: 5.961940
rate Q <-> I: 0.082096
rate Q <-> L: 0.743663
rate Q <-> K: 3.111758
rate Q <-> M: 0.479236
rate Q <-> F: 0.047916
rate Q <-> P: 1.686738
rate Q <-> S: 0.575635
rate Q <-> T: 0.549432
rate Q <-> W: 0.180624
rate Q <-> Y: 0.267198
rate Q <-> V: 0.188559
rate E <-> G: 1.170169
rate E <-> H: 0.255684
rate E <-> I: 0.117237
rate E <-> L: 0.102250
rate E <-> K: 1.816336
rate E <-> M: 0.183643
rate E <-> F: 0.045972
rate E <-> P: 0.201379
rate E <-> S: 0.327723
rate E <-> T: 0.347793
rate E <-> W: 0.119972
rate E <-> Y: 0.066554
rate E <-> V: 0.488015
rate G <-> H: 0.211556
rate G <-> I: 0.056397
rate G <-> L: 0.072889
rate G <-> K: 0.283031
rate G <-> M: 0.136752
rate G <-> F: 0.052667
rate G <-> P: 0.218253
rate G <-> S: 1.965919
rate G <-> T: 0.332351
rate G <-> W: 0.570782
rate G <-> Y: 0.055066
rate G <-> V: 0.493122
rate H <-> I: 0.190675
rate H <-> L: 0.566996
rate H <-> K: 0.550765
rate H <-> M: 0.345775
rate H <-> F: 0.475593
rate H <-> P: 1.197785
rate H <-> S: 0.779801
rate H <-> T: 0.500690
rate H <-> W: 0.134460
rate H <-> Y: 6.134293
rate H <-> V: 0.127782
rate I <-> L: 2.449290
rate I <-> K: 0.212464
rate I <-> M: 5.067857
rate I <-> F: 0.815077
rate I <-> P: 0.103399
rate I <-> S: 0.424923
rate I <-> T: 2.678646
rate I <-> W: 0.141085
rate I <-> Y: 0.318279
rate I <-> V: 10.000000
rate L <-> K: 0.153642
rate L <-> M: 4.045447
rate L <-> F: 2.622518
rate L <-> P: 1.112346
rate L <-> S: 0.621475
rate L <-> T: 0.285836
rate L <-> W: 0.556248
rate L <-> Y: 0.252880
rate L <-> V: 1.847545
rate K <-> M: 0.655113
rate K <-> F: 0.025720
rate K <-> P: 0.226921
rate K <-> S: 0.497672
rate K <-> T: 1.012845
rate K <-> W: 0.093491
rate K <-> Y: 0.092201
rate K <-> V: 0.130131
rate M <-> F: 0.457503
rate M <-> P: 0.172242
rate M <-> S: 0.299524
rate M <-> T: 2.218104
rate M <-> W: 0.211176
rate M <-> Y: 0.199152
rate M <-> V: 3.187069
rate F <-> P: 0.155741
rate F <-> S: 0.990116
rate F <-> T: 0.145694
rate F <-> W: 0.564218
rate F <-> Y: 5.752327
rate F <-> V: 0.622490
rate P <-> S: 2.924714
rate P <-> T: 1.234496
rate P <-> W: 0.073385
rate P <-> Y: 0.119415
rate P <-> V: 0.221903
rate S <-> T: 5.011197
rate S <-> W: 0.326126
rate S <-> Y: 0.659337
rate S <-> V: 0.428503
rate T <-> W: 0.084494
rate T <-> Y: 0.210924
rate T <-> V: 1.199902
rate W <-> Y: 0.784449
rate W <-> V: 0.251414
rate Y <-> V: 0.173562

freq pi(A): 0.054853
freq pi(R): 0.046897
freq pi(N ): 0.032881
freq pi(D): 0.049507
freq pi(C): 0.131460
freq pi(Q): 0.034963
freq pi(E): 0.060758
freq pi(G): 0.071417
freq pi(H): 0.049166
freq pi(I): 0.037791
freq pi(L): 0.063710
freq pi(K): 0.070547
freq pi(M): 0.015135
freq pi(F): 0.055008
freq pi(P): 0.033005
freq pi(S): 0.045281
freq pi(T): 0.038599
freq pi(W): 0.011561
freq pi(Y): 0.046804
freq pi(V): 0.050657

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTTDCMUT/RAxML_result.GF
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTTDCMUT/RAxML_log.GF
