

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: WAG
Empirical Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAWAGF -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GF -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/WAG 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.228296
Subtree Equality Vectors for gap columns full tree traversal time: 1.301759
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/WAG/RAxML_binaryModelParameters.GF


Overall Time for Tree Evaluation 43.681505
Final GAMMA  likelihood: -38835.413552


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.772771
Tree-Length: 133.056809
rate A <-> R: 0.705217
rate A <-> N : 0.651871
rate A <-> D: 0.944853
rate A <-> C: 1.313132
rate A <-> Q: 1.161697
rate A <-> E: 2.023768
rate A <-> G: 1.811361
rate A <-> H: 0.405245
rate A <-> I: 0.247190
rate A <-> L: 0.508758
rate A <-> K: 1.158714
rate A <-> M: 1.142388
rate A <-> F: 0.269129
rate A <-> P: 1.839272
rate A <-> S: 4.309757
rate A <-> T: 2.711966
rate A <-> W: 0.144647
rate A <-> Y: 0.307794
rate A <-> V: 2.564804
rate R <-> N : 0.812328
rate R <-> D: 0.188337
rate R <-> C: 0.675324
rate R <-> Q: 3.881068
rate R <-> E: 0.561488
rate R <-> G: 0.747529
rate R <-> H: 2.732474
rate R <-> I: 0.239064
rate R <-> L: 0.636302
rate R <-> K: 6.842111
rate R <-> M: 0.873463
rate R <-> F: 0.131322
rate R <-> P: 0.868767
rate R <-> S: 1.565200
rate R <-> T: 0.708850
rate R <-> W: 1.488141
rate R <-> Y: 0.487813
rate R <-> V: 0.322004
rate N  <-> D: 6.941838
rate N  <-> C: 0.339146
rate N  <-> Q: 1.973636
rate N  <-> E: 1.211049
rate N  <-> G: 1.439096
rate N  <-> H: 5.058353
rate N  <-> I: 0.708624
rate N  <-> L: 0.168166
rate N  <-> K: 3.851035
rate N  <-> M: 0.253437
rate N  <-> F: 0.122949
rate N  <-> P: 0.249423
rate N  <-> S: 5.081291
rate N  <-> T: 2.595553
rate N  <-> W: 0.091950
rate N  <-> Y: 1.388516
rate N  <-> V: 0.250912
rate D <-> C: 0.038734
rate D <-> Q: 0.788594
rate D <-> E: 7.894033
rate D <-> G: 1.106701
rate D <-> H: 1.189925
rate D <-> I: 0.050423
rate D <-> L: 0.108428
rate D <-> K: 0.613523
rate D <-> M: 0.132656
rate D <-> F: 0.059748
rate D <-> P: 0.542089
rate D <-> S: 1.370309
rate D <-> T: 0.479289
rate D <-> W: 0.165915
rate D <-> Y: 0.416441
rate D <-> V: 0.194769
rate C <-> Q: 0.126345
rate C <-> E: 0.027300
rate C <-> G: 0.392101
rate C <-> H: 0.318326
rate C <-> I: 0.217528
rate C <-> L: 0.491334
rate C <-> K: 0.094657
rate C <-> M: 0.499255
rate C <-> F: 0.508892
rate C <-> P: 0.139880
rate C <-> S: 1.799778
rate C <-> T: 0.655881
rate C <-> W: 0.916817
rate C <-> Y: 0.695323
rate C <-> V: 1.281296
rate Q <-> E: 6.993045
rate Q <-> G: 0.421991
rate Q <-> H: 5.490277
rate Q <-> I: 0.145650
rate Q <-> L: 1.111694
rate Q <-> K: 4.979863
rate Q <-> M: 1.975707
rate Q <-> F: 0.127755
rate Q <-> P: 1.193372
rate Q <-> S: 1.315472
rate Q <-> T: 1.096912
rate Q <-> W: 0.275833
rate Q <-> Y: 0.291141
rate Q <-> V: 0.385206
rate E <-> G: 0.725860
rate E <-> H: 0.728811
rate E <-> I: 0.162882
rate E <-> L: 0.197234
rate E <-> K: 3.304348
rate E <-> M: 0.402905
rate E <-> F: 0.103735
rate E <-> P: 0.872432
rate E <-> S: 0.901307
rate E <-> T: 1.051954
rate E <-> W: 0.200167
rate E <-> Y: 0.250985
rate E <-> V: 0.752728
rate G <-> H: 0.318886
rate G <-> I: 0.038932
rate G <-> L: 0.078380
rate G <-> K: 0.477616
rate G <-> M: 0.222597
rate G <-> F: 0.063840
rate G <-> P: 0.311419
rate G <-> S: 1.715597
rate G <-> T: 0.288741
rate G <-> W: 0.430853
rate G <-> Y: 0.132464
rate G <-> V: 0.239406
rate H <-> I: 0.176684
rate H <-> L: 0.638592
rate H <-> K: 1.138471
rate H <-> M: 0.516718
rate H <-> F: 0.868616
rate H <-> P: 0.890131
rate H <-> S: 0.946350
rate H <-> T: 0.605151
rate H <-> W: 0.335710
rate H <-> Y: 4.952425
rate H <-> V: 0.151328
rate I <-> L: 4.054275
rate I <-> K: 0.414039
rate I <-> M: 5.443417
rate I <-> F: 1.354596
rate I <-> P: 0.127765
rate I <-> S: 0.408423
rate I <-> T: 1.864345
rate I <-> W: 0.271672
rate I <-> Y: 0.537212
rate I <-> V: 10.000000
rate L <-> K: 0.329299
rate L <-> M: 6.206155
rate L <-> F: 2.704371
rate L <-> P: 0.531681
rate L <-> S: 0.440769
rate L <-> T: 0.417606
rate L <-> W: 0.850637
rate L <-> Y: 0.509657
rate L <-> V: 2.301842
rate K <-> M: 1.194528
rate K <-> F: 0.113582
rate K <-> P: 0.712025
rate K <-> S: 1.236534
rate K <-> T: 1.773337
rate K <-> W: 0.175808
rate K <-> Y: 0.170386
rate K <-> V: 0.390516
rate M <-> F: 1.522292
rate M <-> P: 0.219054
rate M <-> S: 0.631487
rate M <-> T: 1.938450
rate M <-> W: 0.659361
rate M <-> Y: 0.547782
rate M <-> V: 2.631851
rate F <-> P: 0.206416
rate F <-> S: 0.698005
rate F <-> T: 0.219788
rate F <-> W: 1.955736
rate F <-> Y: 8.252183
rate F <-> V: 0.830926
rate P <-> S: 2.062675
rate P <-> T: 1.016946
rate P <-> W: 0.178238
rate P <-> Y: 0.276228
rate P <-> V: 0.402602
rate S <-> T: 5.597561
rate S <-> W: 0.669635
rate S <-> Y: 1.006218
rate S <-> V: 0.297571
rate T <-> W: 0.141746
rate T <-> Y: 0.372250
rate T <-> V: 1.774935
rate W <-> Y: 3.177720
rate W <-> V: 0.467146
rate Y <-> V: 0.402401

freq pi(A): 0.054853
freq pi(R): 0.046897
freq pi(N ): 0.032881
freq pi(D): 0.049507
freq pi(C): 0.131460
freq pi(Q): 0.034963
freq pi(E): 0.060758
freq pi(G): 0.071417
freq pi(H): 0.049166
freq pi(I): 0.037791
freq pi(L): 0.063710
freq pi(K): 0.070547
freq pi(M): 0.015135
freq pi(F): 0.055008
freq pi(P): 0.033005
freq pi(S): 0.045281
freq pi(T): 0.038599
freq pi(W): 0.011561
freq pi(Y): 0.046804
freq pi(V): 0.050657

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/WAG/RAxML_result.GF
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/WAG/RAxML_log.GF
