

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: FLU
Fixed Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAFLU -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n G -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/FLU 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.224239
Subtree Equality Vectors for gap columns full tree traversal time: 1.296856
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/FLU/RAxML_binaryModelParameters.G


Overall Time for Tree Evaluation 33.776712
Final GAMMA  likelihood: -39687.060013


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.993144
Tree-Length: 207.147932
rate A <-> R: 0.090626
rate A <-> N : 0.034880
rate A <-> D: 0.382254
rate A <-> C: 0.017286
rate A <-> Q: 0.231210
rate A <-> E: 0.970082
rate A <-> G: 0.740069
rate A <-> H: 0.140364
rate A <-> I: 0.097991
rate A <-> L: 0.015109
rate A <-> K: 0.310020
rate A <-> M: 0.038395
rate A <-> F: 0.052608
rate A <-> P: 0.430920
rate A <-> S: 1.968187
rate A <-> T: 3.541349
rate A <-> W: 0.128104
rate A <-> Y: 0.011954
rate A <-> V: 2.308486
rate R <-> N : 0.105229
rate R <-> D: 0.004426
rate R <-> C: 0.109285
rate R <-> Q: 2.152089
rate R <-> E: 0.081632
rate R <-> G: 0.778181
rate R <-> H: 1.228469
rate R <-> I: 0.160860
rate R <-> L: 0.193493
rate R <-> K: 10.000000
rate R <-> M: 0.581802
rate R <-> F: 0.010523
rate R <-> P: 0.100671
rate R <-> S: 0.621002
rate R <-> T: 0.119657
rate R <-> W: 0.895046
rate R <-> Y: 0.065265
rate R <-> V: 0.067950
rate N  <-> D: 5.057088
rate N  <-> C: 0.000008
rate N  <-> Q: 0.346823
rate N  <-> E: 0.040295
rate N  <-> G: 0.210799
rate N  <-> H: 0.906593
rate N  <-> I: 0.142857
rate N  <-> L: 0.000546
rate N  <-> K: 1.729955
rate N  <-> M: 0.003432
rate N  <-> F: 0.000546
rate N  <-> P: 0.023791
rate N  <-> S: 2.536788
rate N  <-> T: 1.398901
rate N  <-> W: 0.000350
rate N  <-> Y: 0.243856
rate N  <-> V: 0.006704
rate D <-> C: 0.009216
rate D <-> Q: 0.095077
rate D <-> E: 3.510116
rate D <-> G: 1.264589
rate D <-> H: 0.580108
rate D <-> I: 0.009206
rate D <-> L: 0.003746
rate D <-> K: 0.189569
rate D <-> M: 0.027296
rate D <-> F: 0.000001
rate D <-> P: 0.123228
rate D <-> S: 0.221157
rate D <-> T: 0.088549
rate D <-> W: 0.000010
rate D <-> Y: 0.343396
rate D <-> V: 0.194197
rate C <-> Q: 0.001665
rate C <-> E: 0.000000
rate C <-> G: 0.076432
rate C <-> H: 0.014248
rate C <-> I: 0.000727
rate C <-> L: 0.003669
rate C <-> K: 0.000003
rate C <-> M: 0.072847
rate C <-> F: 0.068009
rate C <-> P: 0.000000
rate C <-> S: 0.219779
rate C <-> T: 0.007827
rate C <-> W: 0.061507
rate C <-> Y: 0.393261
rate C <-> V: 0.035885
rate Q <-> E: 0.781452
rate Q <-> G: 0.070621
rate Q <-> H: 3.483843
rate Q <-> I: 0.018850
rate Q <-> L: 0.666902
rate Q <-> K: 1.672922
rate Q <-> M: 0.124352
rate Q <-> F: 0.021360
rate Q <-> P: 0.465860
rate Q <-> S: 0.318836
rate Q <-> T: 0.393684
rate Q <-> W: 0.028758
rate Q <-> Y: 0.047193
rate Q <-> V: 0.265814
rate E <-> G: 1.041234
rate E <-> H: 0.167641
rate E <-> I: 0.009281
rate E <-> L: 0.010784
rate E <-> K: 2.536905
rate E <-> M: 0.205211
rate E <-> F: 0.000656
rate E <-> P: 0.208861
rate E <-> S: 0.200744
rate E <-> T: 0.183087
rate E <-> W: 0.101467
rate E <-> Y: 0.068034
rate E <-> V: 0.186305
rate G <-> H: 0.038414
rate G <-> I: 0.000011
rate G <-> L: 0.004259
rate G <-> K: 0.172645
rate G <-> M: 0.000981
rate G <-> F: 0.000808
rate G <-> P: 0.025249
rate G <-> S: 1.036364
rate G <-> T: 0.012293
rate G <-> W: 0.128422
rate G <-> Y: 0.048898
rate G <-> V: 0.220410
rate H <-> I: 0.158947
rate H <-> L: 0.210202
rate H <-> K: 0.226994
rate H <-> M: 0.000832
rate H <-> F: 0.077796
rate H <-> P: 0.604223
rate H <-> S: 0.379543
rate H <-> T: 0.240988
rate H <-> W: 0.014640
rate H <-> Y: 4.214976
rate H <-> V: 0.064465
rate I <-> L: 2.295458
rate I <-> K: 0.148828
rate I <-> M: 5.894050
rate I <-> F: 0.956437
rate I <-> P: 0.052642
rate I <-> S: 0.189790
rate I <-> T: 1.898061
rate I <-> W: 0.021001
rate I <-> Y: 0.179041
rate I <-> V: 9.407818
rate L <-> K: 0.084459
rate L <-> M: 4.409735
rate L <-> F: 1.952145
rate L <-> P: 0.414578
rate L <-> S: 0.373048
rate L <-> T: 0.029363
rate L <-> W: 0.281879
rate L <-> Y: 0.222259
rate L <-> V: 0.582087
rate K <-> M: 0.870120
rate K <-> F: 0.209149
rate K <-> P: 0.127941
rate K <-> S: 0.185494
rate K <-> T: 0.998010
rate K <-> W: 0.000033
rate K <-> Y: 0.008115
rate K <-> V: 0.047796
rate M <-> F: 0.182947
rate M <-> P: 0.037189
rate M <-> S: 0.004593
rate M <-> T: 1.327777
rate M <-> W: 0.046052
rate M <-> Y: 0.571416
rate M <-> V: 3.205759
rate F <-> P: 0.004662
rate F <-> S: 0.651424
rate F <-> T: 0.000088
rate F <-> W: 0.532515
rate F <-> Y: 3.525418
rate F <-> V: 0.387310
rate P <-> S: 1.364296
rate P <-> T: 0.354410
rate P <-> W: 0.000282
rate P <-> Y: 0.000119
rate P <-> V: 0.038544
rate S <-> T: 1.442383
rate S <-> W: 0.065252
rate S <-> Y: 0.256568
rate S <-> V: 0.057684
rate T <-> W: 0.135337
rate T <-> Y: 0.081632
rate T <-> V: 0.427520
rate W <-> Y: 0.279577
rate W <-> V: 0.167908
rate Y <-> V: 0.109530

freq pi(A): 0.047100
freq pi(R): 0.050900
freq pi(N ): 0.074200
freq pi(D): 0.047900
freq pi(C): 0.025000
freq pi(Q): 0.033300
freq pi(E): 0.054600
freq pi(G): 0.076400
freq pi(H): 0.020000
freq pi(I): 0.067100
freq pi(L): 0.071500
freq pi(K): 0.056800
freq pi(M): 0.018100
freq pi(F): 0.030500
freq pi(P): 0.050700
freq pi(S): 0.088400
freq pi(T): 0.074300
freq pi(W): 0.018500
freq pi(Y): 0.031500
freq pi(V): 0.063200

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/FLU/RAxML_result.G
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/FLU/RAxML_log.G
