

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: JTT
Empirical Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAJTTF -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GF -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTT 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.285149
Subtree Equality Vectors for gap columns full tree traversal time: 1.353664
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTT/RAxML_binaryModelParameters.GF


Overall Time for Tree Evaluation 47.853495
Final GAMMA  likelihood: -39157.179328


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.747856
Tree-Length: 145.884364
rate A <-> R: 0.603538
rate A <-> N : 0.561915
rate A <-> D: 0.842872
rate A <-> C: 0.582726
rate A <-> Q: 0.593132
rate A <-> E: 1.092612
rate A <-> G: 1.862643
rate A <-> H: 0.280957
rate A <-> I: 0.374610
rate A <-> L: 0.312175
rate A <-> K: 0.364204
rate A <-> M: 0.561915
rate A <-> F: 0.156087
rate A <-> P: 2.018730
rate A <-> S: 3.933403
rate A <-> T: 4.942768
rate A <-> W: 0.093652
rate A <-> Y: 0.114464
rate A <-> V: 3.100937
rate R <-> N : 0.468262
rate R <-> D: 0.166493
rate R <-> C: 1.175858
rate R <-> Q: 3.225806
rate R <-> E: 0.301769
rate R <-> G: 1.425598
rate R <-> H: 3.413111
rate R <-> I: 0.228928
rate R <-> L: 0.395421
rate R <-> K: 6.722164
rate R <-> M: 0.457856
rate R <-> F: 0.052029
rate R <-> P: 0.770031
rate R <-> S: 1.050989
rate R <-> T: 0.665973
rate R <-> W: 1.311134
rate R <-> Y: 0.208117
rate R <-> V: 0.176899
rate N  <-> D: 5.494277
rate N  <-> C: 0.353798
rate N  <-> Q: 0.894901
rate N  <-> E: 0.603538
rate N  <-> G: 0.842872
rate N  <-> H: 4.068678
rate N  <-> I: 0.489074
rate N  <-> L: 0.124870
rate N  <-> K: 2.736733
rate N  <-> M: 0.312175
rate N  <-> F: 0.104058
rate N  <-> P: 0.156087
rate N  <-> S: 5.234131
rate N  <-> T: 2.414152
rate N  <-> W: 0.083247
rate N  <-> Y: 0.728408
rate N  <-> V: 0.166493
rate D <-> C: 0.104058
rate D <-> Q: 0.509886
rate D <-> E: 7.981270
rate D <-> G: 1.352758
rate D <-> H: 1.165453
rate D <-> I: 0.114464
rate D <-> L: 0.072841
rate D <-> K: 0.270552
rate D <-> M: 0.156087
rate D <-> F: 0.041623
rate D <-> P: 0.156087
rate D <-> S: 0.613944
rate D <-> T: 0.395421
rate D <-> W: 0.041623
rate D <-> Y: 0.478668
rate D <-> V: 0.322581
rate C <-> Q: 0.093652
rate C <-> E: 0.052029
rate C <-> G: 0.613944
rate C <-> H: 0.718002
rate C <-> I: 0.176899
rate C <-> L: 0.239334
rate C <-> K: 0.072841
rate C <-> M: 0.322581
rate C <-> F: 0.811655
rate C <-> P: 0.145682
rate C <-> S: 2.320499
rate C <-> T: 0.437045
rate C <-> W: 1.196670
rate C <-> Y: 2.174818
rate C <-> V: 0.645161
rate Q <-> E: 3.361082
rate Q <-> G: 0.270552
rate Q <-> H: 6.212279
rate Q <-> I: 0.093652
rate Q <-> L: 0.749220
rate Q <-> K: 3.038502
rate Q <-> M: 0.447451
rate Q <-> F: 0.041623
rate Q <-> P: 1.706556
rate Q <-> S: 0.551509
rate Q <-> T: 0.530697
rate Q <-> W: 0.187305
rate Q <-> Y: 0.249740
rate Q <-> V: 0.208117
rate E <-> G: 1.238293
rate E <-> H: 0.270552
rate E <-> I: 0.124870
rate E <-> L: 0.093652
rate E <-> K: 1.883455
rate E <-> M: 0.187305
rate E <-> F: 0.052029
rate E <-> P: 0.187305
rate E <-> S: 0.312175
rate E <-> T: 0.332986
rate E <-> W: 0.104058
rate E <-> Y: 0.072841
rate E <-> V: 0.468262
rate G <-> H: 0.239334
rate G <-> I: 0.062435
rate G <-> L: 0.062435
rate G <-> K: 0.280957
rate G <-> M: 0.145682
rate G <-> F: 0.052029
rate G <-> P: 0.249740
rate G <-> S: 2.091571
rate G <-> T: 0.343392
rate G <-> W: 0.572320
rate G <-> Y: 0.083247
rate G <-> V: 0.489074
rate H <-> I: 0.166493
rate H <-> L: 0.582726
rate H <-> K: 0.468262
rate H <-> M: 0.343392
rate H <-> F: 0.416233
rate H <-> P: 1.196670
rate H <-> S: 0.759625
rate H <-> T: 0.478668
rate H <-> W: 0.083247
rate H <-> Y: 5.962539
rate H <-> V: 0.114464
rate I <-> L: 2.382934
rate I <-> K: 0.218522
rate I <-> M: 4.984391
rate I <-> F: 0.926119
rate I <-> P: 0.104058
rate I <-> S: 0.416233
rate I <-> T: 2.549428
rate I <-> W: 0.093652
rate I <-> Y: 0.332986
rate I <-> V: 10.000000
rate L <-> K: 0.145682
rate L <-> M: 4.037461
rate L <-> F: 2.580645
rate L <-> P: 1.061394
rate L <-> S: 0.613944
rate L <-> T: 0.260146
rate L <-> W: 0.541103
rate L <-> Y: 0.249740
rate L <-> V: 1.873049
rate K <-> M: 0.676379
rate K <-> F: 0.041623
rate K <-> P: 0.218522
rate K <-> S: 0.489074
rate K <-> T: 1.071800
rate K <-> W: 0.104058
rate K <-> Y: 0.083247
rate K <-> V: 0.145682
rate M <-> F: 0.447451
rate M <-> P: 0.166493
rate M <-> S: 0.301769
rate M <-> T: 2.351717
rate M <-> W: 0.249740
rate M <-> Y: 0.187305
rate M <-> V: 3.361082
rate F <-> P: 0.176899
rate F <-> S: 0.957336
rate F <-> T: 0.124870
rate F <-> W: 0.551509
rate F <-> Y: 5.577523
rate F <-> V: 0.645161
rate P <-> S: 2.965661
rate P <-> T: 1.227888
rate P <-> W: 0.062435
rate P <-> Y: 0.104058
rate P <-> V: 0.239334
rate S <-> T: 4.963580
rate S <-> W: 0.364204
rate S <-> Y: 0.655567
rate S <-> V: 0.395421
rate T <-> W: 0.124870
rate T <-> Y: 0.218522
rate T <-> V: 1.165453
rate W <-> Y: 0.738814
rate W <-> V: 0.260146
rate Y <-> V: 0.166493

freq pi(A): 0.054853
freq pi(R): 0.046897
freq pi(N ): 0.032881
freq pi(D): 0.049507
freq pi(C): 0.131460
freq pi(Q): 0.034963
freq pi(E): 0.060758
freq pi(G): 0.071417
freq pi(H): 0.049166
freq pi(I): 0.037791
freq pi(L): 0.063710
freq pi(K): 0.070547
freq pi(M): 0.015135
freq pi(F): 0.055008
freq pi(P): 0.033005
freq pi(S): 0.045281
freq pi(T): 0.038599
freq pi(W): 0.011561
freq pi(Y): 0.046804
freq pi(V): 0.050657

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTT/RAxML_result.GF
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/JTT/RAxML_log.GF
