

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: MTREV
Empirical Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAMTREVF -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GF -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTREV 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.226211
Subtree Equality Vectors for gap columns full tree traversal time: 1.300655
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTREV/RAxML_binaryModelParameters.GF


Overall Time for Tree Evaluation 43.122787
Final GAMMA  likelihood: -40155.524259


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.690209
Tree-Length: 177.968949
rate A <-> R: 0.189543
rate A <-> N : 0.220371
rate A <-> D: 0.144488
rate A <-> C: 0.490049
rate A <-> Q: 0.015536
rate A <-> E: 0.079889
rate A <-> G: 0.987048
rate A <-> H: 0.113661
rate A <-> I: 0.789000
rate A <-> L: 0.208187
rate A <-> K: 0.068360
rate A <-> M: 1.160155
rate A <-> F: 0.052088
rate A <-> P: 0.444094
rate A <-> S: 3.171537
rate A <-> T: 3.930855
rate A <-> W: 0.015536
rate A <-> Y: 0.052987
rate A <-> V: 1.595009
rate R <-> N : 0.108264
rate R <-> D: 0.015536
rate R <-> C: 0.844931
rate R <-> Q: 1.807039
rate R <-> E: 0.015536
rate R <-> G: 0.188317
rate R <-> H: 1.351088
rate R <-> I: 0.015536
rate R <-> L: 0.127398
rate R <-> K: 1.156230
rate R <-> M: 0.015536
rate R <-> F: 0.038350
rate R <-> P: 0.193305
rate R <-> S: 0.049389
rate R <-> T: 0.017008
rate R <-> W: 0.179486
rate R <-> Y: 0.015536
rate R <-> V: 0.062472
rate N  <-> D: 6.495658
rate N  <-> C: 0.481953
rate N  <-> Q: 1.419203
rate N  <-> E: 0.515561
rate N  <-> G: 0.435835
rate N  <-> H: 4.056863
rate N  <-> I: 0.221597
rate N  <-> L: 0.123964
rate N  <-> K: 4.977350
rate N  <-> M: 0.534859
rate N  <-> F: 0.124291
rate N  <-> P: 0.599457
rate N  <-> S: 4.042635
rate N  <-> T: 1.949891
rate N  <-> W: 0.087331
rate N  <-> Y: 1.564754
rate N  <-> V: 0.015536
rate D <-> C: 0.015536
rate D <-> Q: 0.452025
rate D <-> E: 4.771698
rate D <-> G: 0.464209
rate D <-> H: 0.932098
rate D <-> I: 0.035488
rate D <-> L: 0.015536
rate D <-> K: 0.018889
rate D <-> M: 0.015536
rate D <-> F: 0.040722
rate D <-> P: 0.109817
rate D <-> S: 0.564378
rate D <-> T: 0.229038
rate D <-> W: 0.162396
rate D <-> Y: 0.173435
rate D <-> V: 0.015536
rate C <-> Q: 0.615239
rate C <-> E: 0.015536
rate C <-> G: 0.251116
rate C <-> H: 1.156966
rate C <-> I: 0.512944
rate C <-> L: 0.209740
rate C <-> K: 0.015536
rate C <-> M: 0.050534
rate C <-> F: 0.578933
rate C <-> P: 0.255614
rate C <-> S: 2.265442
rate C <-> T: 1.471618
rate C <-> W: 0.274748
rate C <-> Y: 2.083258
rate C <-> V: 0.015536
rate Q <-> E: 2.563985
rate Q <-> G: 0.055195
rate Q <-> H: 4.762294
rate Q <-> I: 0.068196
rate Q <-> L: 0.324628
rate Q <-> K: 3.807055
rate Q <-> M: 0.387345
rate Q <-> F: 0.156263
rate Q <-> P: 1.122623
rate Q <-> S: 0.442458
rate Q <-> T: 0.776244
rate Q <-> W: 0.015536
rate Q <-> Y: 0.317432
rate Q <-> V: 0.155363
rate E <-> G: 0.231246
rate E <-> H: 0.401655
rate E <-> I: 0.027066
rate E <-> L: 0.015536
rate E <-> K: 2.566438
rate E <-> M: 0.015536
rate E <-> F: 0.021833
rate E <-> P: 0.104911
rate E <-> S: 0.447365
rate E <-> T: 0.121183
rate E <-> W: 0.015536
rate E <-> Y: 0.107282
rate E <-> V: 0.172862
rate G <-> H: 0.015536
rate G <-> I: 0.048899
rate G <-> L: 0.019707
rate G <-> K: 0.185864
rate G <-> M: 0.015536
rate G <-> F: 0.015536
rate G <-> P: 0.015536
rate G <-> S: 1.029732
rate G <-> T: 0.091337
rate G <-> W: 0.089293
rate G <-> Y: 0.026248
rate G <-> V: 0.020688
rate H <-> I: 0.100250
rate H <-> L: 0.093954
rate H <-> K: 1.043960
rate H <-> M: 0.097879
rate H <-> F: 0.393805
rate H <-> P: 0.498553
rate H <-> S: 0.633392
rate H <-> T: 0.366167
rate H <-> W: 0.057893
rate H <-> Y: 5.479746
rate H <-> V: 0.015536
rate I <-> L: 2.690974
rate I <-> K: 0.160024
rate I <-> M: 4.235531
rate I <-> F: 0.692348
rate I <-> P: 0.168692
rate I <-> S: 0.390044
rate I <-> T: 3.012658
rate I <-> W: 0.015536
rate I <-> Y: 0.204507
rate I <-> V: 10.000000
rate L <-> K: 0.121674
rate L <-> M: 4.395391
rate L <-> F: 1.766726
rate L <-> P: 0.327898
rate L <-> S: 0.601910
rate L <-> T: 1.033575
rate L <-> W: 0.265262
rate L <-> Y: 0.361015
rate L <-> V: 0.749587
rate K <-> M: 0.747134
rate K <-> F: 0.052660
rate K <-> P: 0.409669
rate K <-> S: 0.865047
rate K <-> T: 1.114773
rate K <-> W: 0.196248
rate K <-> Y: 0.418418
rate K <-> V: 0.015536
rate M <-> F: 0.742637
rate M <-> P: 0.154055
rate M <-> S: 0.908957
rate M <-> T: 4.318855
rate M <-> W: 0.177523
rate M <-> Y: 0.326754
rate M <-> V: 3.168921
rate F <-> P: 0.141544
rate F <-> S: 0.525700
rate F <-> T: 0.276792
rate F <-> W: 0.064108
rate F <-> Y: 3.807055
rate F <-> V: 0.051924
rate P <-> S: 1.389275
rate P <-> T: 1.048457
rate P <-> W: 0.034425
rate P <-> Y: 0.132549
rate P <-> V: 0.067297
rate S <-> T: 4.883396
rate S <-> W: 0.315469
rate S <-> Y: 0.530852
rate S <-> V: 0.015536
rate T <-> W: 0.081688
rate T <-> Y: 0.316696
rate T <-> V: 1.672527
rate W <-> Y: 0.214647
rate W <-> V: 0.043911
rate Y <-> V: 0.015536

freq pi(A): 0.054853
freq pi(R): 0.046897
freq pi(N ): 0.032881
freq pi(D): 0.049507
freq pi(C): 0.131460
freq pi(Q): 0.034963
freq pi(E): 0.060758
freq pi(G): 0.071417
freq pi(H): 0.049166
freq pi(I): 0.037791
freq pi(L): 0.063710
freq pi(K): 0.070547
freq pi(M): 0.015135
freq pi(F): 0.055008
freq pi(P): 0.033005
freq pi(S): 0.045281
freq pi(T): 0.038599
freq pi(W): 0.011561
freq pi(Y): 0.046804
freq pi(V): 0.050657

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTREV/RAxML_result.GF
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/MTREV/RAxML_log.GF
