
You are using a proportion of Invariable sites estimate, although I don't
like it. The likelihood epsilon "-f e" will be automatically lowered to 0.001
to avoid unfavorable effects caused by simultaneous optimization of alpha and P-Invar


IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Found 0 invariant alignment patterns that correspond to 0 columns 
Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.001000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA+P-Invar model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA+P-Invar Model parameters will be estimated up to an accuracy of 0.0010000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: DAYHOFF
Fixed Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAIDAYHOFF -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GI -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DAYHOFF 



Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DAYHOFF/RAxML_binaryModelParameters.GI


Overall Time for Tree Evaluation 51.016140
Final GAMMA  likelihood: -39039.449973


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.962623
invar: 0.054804
Tree-Length: 170.556079
rate A <-> R: 0.234172
rate A <-> N : 0.849957
rate A <-> D: 1.040763
rate A <-> C: 0.312229
rate A <-> Q: 0.771899
rate A <-> E: 1.717259
rate A <-> G: 2.081526
rate A <-> H: 0.199480
rate A <-> I: 0.563747
rate A <-> L: 0.355594
rate A <-> K: 0.225499
rate A <-> M: 0.624458
rate A <-> F: 0.156114
rate A <-> P: 2.168257
rate A <-> S: 3.547268
rate A <-> T: 3.217693
rate A <-> W: 0.000000
rate A <-> Y: 0.208153
rate A <-> V: 1.803990
rate R <-> N : 0.277537
rate R <-> D: 0.000000
rate R <-> C: 0.199480
rate R <-> Q: 2.133565
rate R <-> E: 0.008673
rate R <-> G: 0.078057
rate R <-> H: 2.081526
rate R <-> I: 0.555074
rate R <-> L: 0.130095
rate R <-> K: 4.024284
rate R <-> M: 0.780572
rate R <-> F: 0.121422
rate R <-> P: 0.893322
rate R <-> S: 1.335646
rate R <-> T: 0.225499
rate R <-> W: 1.743278
rate R <-> Y: 0.069384
rate R <-> V: 0.208153
rate N  <-> D: 7.849089
rate N  <-> C: 0.000000
rate N  <-> Q: 0.893322
rate N  <-> E: 1.283608
rate N  <-> G: 1.205551
rate N  <-> H: 4.640069
rate N  <-> I: 0.667823
rate N  <-> L: 0.294883
rate N  <-> K: 2.758023
rate N  <-> M: 0.008673
rate N  <-> F: 0.121422
rate N  <-> P: 0.364267
rate N  <-> S: 4.293148
rate N  <-> T: 1.986123
rate N  <-> W: 0.199480
rate N  <-> Y: 0.823938
rate N  <-> V: 0.130095
rate D <-> C: 0.000000
rate D <-> Q: 1.162186
rate D <-> E: 10.000000
rate D <-> G: 1.084128
rate D <-> H: 0.745880
rate D <-> I: 0.208153
rate D <-> L: 0.000000
rate D <-> K: 0.615785
rate D <-> M: 0.000000
rate D <-> F: 0.000000
rate D <-> P: 0.112749
rate D <-> S: 0.823938
rate D <-> T: 0.572420
rate D <-> W: 0.000000
rate D <-> Y: 0.000000
rate D <-> V: 0.156114
rate C <-> Q: 0.000000
rate C <-> E: 0.000000
rate C <-> G: 0.095403
rate C <-> H: 0.242845
rate C <-> I: 0.381613
rate C <-> L: 0.000000
rate C <-> K: 0.000000
rate C <-> M: 0.000000
rate C <-> F: 0.000000
rate C <-> P: 0.164788
rate C <-> S: 1.396357
rate C <-> T: 0.138768
rate C <-> W: 0.000000
rate C <-> Y: 0.832611
rate C <-> V: 0.424978
rate Q <-> E: 6.209887
rate Q <-> G: 0.242845
rate Q <-> H: 5.255854
rate Q <-> I: 0.156114
rate Q <-> L: 0.633131
rate Q <-> K: 1.326973
rate Q <-> M: 0.988725
rate Q <-> F: 0.000000
rate Q <-> P: 1.326973
rate Q <-> S: 0.485690
rate Q <-> T: 0.459670
rate Q <-> W: 0.000000
rate Q <-> Y: 0.000000
rate Q <-> V: 0.303556
rate E <-> G: 0.702515
rate E <-> H: 0.372940
rate E <-> I: 0.529055
rate E <-> L: 0.095403
rate E <-> K: 0.719861
rate E <-> M: 0.260191
rate E <-> F: 0.000000
rate E <-> P: 0.442324
rate E <-> S: 0.685169
rate E <-> T: 0.294883
rate E <-> W: 0.000000
rate E <-> Y: 0.190807
rate E <-> V: 0.320902
rate G <-> H: 0.086730
rate G <-> I: 0.000000
rate G <-> L: 0.060711
rate G <-> K: 0.234172
rate G <-> M: 0.147441
rate G <-> F: 0.130095
rate G <-> P: 0.294883
rate G <-> S: 2.029488
rate G <-> T: 0.260191
rate G <-> W: 0.000000
rate G <-> Y: 0.000000
rate G <-> V: 0.468343
rate H <-> I: 0.060711
rate H <-> L: 0.381613
rate H <-> K: 0.225499
rate H <-> M: 0.000000
rate H <-> F: 0.416305
rate H <-> P: 0.815265
rate H <-> S: 0.303556
rate H <-> T: 0.190807
rate H <-> W: 0.234172
rate H <-> Y: 1.101474
rate H <-> V: 0.381613
rate I <-> L: 2.228968
rate I <-> K: 0.398959
rate I <-> M: 2.914137
rate I <-> F: 1.699913
rate I <-> P: 0.104076
rate I <-> S: 0.208153
rate I <-> T: 1.665221
rate I <-> W: 0.000000
rate I <-> Y: 0.320902
rate I <-> V: 7.710321
rate L <-> K: 0.156114
rate L <-> M: 4.570685
rate L <-> F: 1.361665
rate L <-> P: 0.277537
rate L <-> S: 0.147441
rate L <-> T: 0.286210
rate L <-> W: 0.398959
rate L <-> Y: 0.242845
rate L <-> V: 1.517780
rate K <-> M: 2.107546
rate K <-> F: 0.000000
rate K <-> P: 0.286210
rate K <-> S: 0.832611
rate K <-> T: 1.179532
rate K <-> W: 0.000000
rate K <-> Y: 0.112749
rate K <-> V: 0.086730
rate M <-> F: 0.797918
rate M <-> P: 0.147441
rate M <-> S: 0.537728
rate M <-> T: 0.901995
rate M <-> W: 0.000000
rate M <-> Y: 0.000000
rate M <-> V: 2.237641
rate F <-> P: 0.095403
rate F <-> S: 0.398959
rate F <-> T: 0.112749
rate F <-> W: 0.659150
rate F <-> Y: 6.053773
rate F <-> V: 0.104076
rate P <-> S: 2.124892
rate P <-> T: 0.676496
rate P <-> W: 0.000000
rate P <-> Y: 0.000000
rate P <-> V: 0.416305
rate S <-> T: 4.770165
rate S <-> W: 0.650477
rate S <-> Y: 0.294883
rate S <-> V: 0.260191
rate T <-> W: 0.000000
rate T <-> Y: 0.364267
rate T <-> V: 1.361665
rate W <-> Y: 0.529055
rate W <-> V: 0.000000
rate Y <-> V: 0.242845

freq pi(A): 0.087000
freq pi(R): 0.041000
freq pi(N ): 0.040000
freq pi(D): 0.047000
freq pi(C): 0.034000
freq pi(Q): 0.038000
freq pi(E): 0.050000
freq pi(G): 0.089000
freq pi(H): 0.034000
freq pi(I): 0.037000
freq pi(L): 0.085000
freq pi(K): 0.080000
freq pi(M): 0.014000
freq pi(F): 0.040000
freq pi(P): 0.051000
freq pi(S): 0.070000
freq pi(T): 0.058000
freq pi(W): 0.011000
freq pi(Y): 0.030000
freq pi(V): 0.064000

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DAYHOFF/RAxML_result.GI
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DAYHOFF/RAxML_log.GI
