

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: BLOSUM62
Fixed Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMABLOSUM62 -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n G -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/BLOSUM62 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.229244
Subtree Equality Vectors for gap columns full tree traversal time: 1.299871
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/BLOSUM62/RAxML_binaryModelParameters.G


Overall Time for Tree Evaluation 57.452719
Final GAMMA  likelihood: -38746.875438


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.696655
Tree-Length: 136.940814
rate A <-> R: 0.885232
rate A <-> N : 0.583975
rate A <-> D: 0.653480
rate A <-> C: 1.756525
rate A <-> Q: 1.443370
rate A <-> E: 1.408772
rate A <-> G: 2.353130
rate A <-> H: 0.861712
rate A <-> I: 0.728959
rate A <-> L: 0.962502
rate A <-> K: 1.558261
rate A <-> M: 1.508400
rate A <-> F: 0.593087
rate A <-> P: 1.411572
rate A <-> S: 5.203533
rate A <-> T: 2.080379
rate A <-> W: 0.560453
rate A <-> Y: 0.864077
rate A <-> V: 2.632118
rate R <-> N : 1.560962
rate R <-> D: 0.602712
rate R <-> C: 0.274099
rate R <-> Q: 3.634374
rate R <-> E: 1.636911
rate R <-> G: 0.503815
rate R <-> H: 1.751888
rate R <-> I: 0.279164
rate R <-> L: 0.749186
rate R <-> K: 6.510130
rate R <-> M: 1.183484
rate R <-> F: 0.447127
rate R <-> P: 0.539151
rate R <-> S: 1.350824
rate R <-> T: 1.100437
rate R <-> W: 0.512982
rate R <-> Y: 0.866857
rate R <-> V: 0.527426
rate N  <-> D: 3.825988
rate N  <-> C: 0.478064
rate N  <-> Q: 2.212767
rate N  <-> E: 1.492436
rate N  <-> G: 1.631254
rate N  <-> H: 2.904894
rate N  <-> I: 0.340499
rate N  <-> L: 0.254923
rate N  <-> K: 1.916708
rate N  <-> M: 0.780142
rate N  <-> F: 0.426935
rate N  <-> P: 0.595400
rate N  <-> S: 3.493934
rate N  <-> T: 2.283699
rate N  <-> W: 0.230373
rate N  <-> Y: 0.647537
rate N  <-> V: 0.376401
rate D <-> C: 0.289751
rate D <-> Q: 1.432831
rate D <-> E: 4.525623
rate D <-> G: 0.960646
rate D <-> H: 0.936186
rate D <-> I: 0.503566
rate D <-> L: 0.262435
rate D <-> K: 1.242141
rate D <-> M: 0.267837
rate D <-> F: 0.338951
rate D <-> P: 0.879021
rate D <-> S: 1.904216
rate D <-> T: 1.123924
rate D <-> W: 0.174865
rate D <-> Y: 0.314518
rate D <-> V: 0.310556
rate C <-> Q: 0.396785
rate C <-> E: 0.169335
rate C <-> G: 0.503142
rate C <-> H: 0.425968
rate C <-> I: 0.932277
rate C <-> L: 1.000792
rate C <-> K: 0.342979
rate C <-> M: 0.923609
rate C <-> F: 0.530974
rate C <-> P: 0.428315
rate C <-> S: 1.440341
rate C <-> T: 1.347273
rate C <-> W: 0.634835
rate C <-> Y: 0.565744
rate C <-> V: 1.343087
rate Q <-> E: 6.651860
rate Q <-> G: 0.733708
rate Q <-> H: 2.929967
rate Q <-> I: 0.284176
rate Q <-> L: 0.698687
rate Q <-> K: 4.746576
rate Q <-> M: 3.001617
rate Q <-> F: 0.173676
rate Q <-> P: 1.032949
rate Q <-> S: 2.327849
rate Q <-> T: 1.536941
rate Q <-> W: 0.912739
rate Q <-> Y: 1.153764
rate Q <-> V: 0.638590
rate E <-> G: 0.509610
rate E <-> H: 1.957318
rate E <-> I: 0.224797
rate E <-> L: 0.448307
rate E <-> K: 3.371609
rate E <-> M: 0.668222
rate E <-> F: 0.350595
rate E <-> P: 1.114752
rate E <-> S: 2.129364
rate E <-> T: 1.288640
rate E <-> W: 0.490428
rate E <-> Y: 0.717915
rate E <-> V: 0.630731
rate G <-> H: 0.649506
rate G <-> I: 0.227743
rate G <-> L: 0.261941
rate G <-> K: 0.904785
rate G <-> M: 0.552749
rate G <-> F: 0.442942
rate G <-> P: 0.606468
rate G <-> S: 1.815875
rate G <-> T: 0.771714
rate G <-> W: 0.611608
rate G <-> Y: 0.370623
rate G <-> V: 0.304795
rate H <-> I: 0.304046
rate H <-> L: 0.418767
rate H <-> K: 1.230181
rate H <-> M: 1.184228
rate H <-> F: 0.859658
rate H <-> P: 0.634044
rate H <-> S: 1.343902
rate H <-> T: 0.704305
rate H <-> W: 0.362433
rate H <-> Y: 5.075837
rate H <-> V: 0.242493
rate I <-> L: 4.681231
rate I <-> K: 0.488693
rate I <-> M: 4.048199
rate I <-> F: 1.825540
rate I <-> P: 0.467232
rate I <-> S: 0.430163
rate I <-> T: 1.418568
rate I <-> W: 0.411444
rate I <-> Y: 0.811634
rate I <-> V: 10.000000
rate L <-> K: 0.536067
rate L <-> M: 7.255385
rate L <-> F: 2.484215
rate L <-> P: 0.450629
rate L <-> S: 0.424658
rate L <-> T: 1.101152
rate L <-> W: 0.831915
rate L <-> Y: 0.976012
rate L <-> V: 2.684611
rate K <-> M: 1.291003
rate K <-> F: 0.321138
rate K <-> P: 1.260110
rate K <-> S: 2.108036
rate K <-> T: 1.568696
rate K <-> W: 0.399723
rate K <-> Y: 0.863820
rate K <-> V: 0.599312
rate M <-> F: 2.134131
rate M <-> P: 0.546358
rate M <-> S: 1.105319
rate M <-> T: 1.790877
rate M <-> W: 1.068477
rate M <-> Y: 1.144972
rate M <-> V: 3.099014
rate F <-> P: 0.281042
rate F <-> S: 0.649709
rate F <-> T: 0.587362
rate F <-> W: 2.495627
rate F <-> Y: 8.117650
rate F <-> V: 1.008344
rate P <-> S: 1.406583
rate P <-> T: 1.209662
rate P <-> W: 0.303440
rate P <-> Y: 0.444433
rate P <-> V: 0.597832
rate S <-> T: 6.197853
rate S <-> W: 0.466715
rate S <-> Y: 0.958574
rate S <-> V: 0.676054
rate T <-> W: 0.617346
rate T <-> Y: 0.963698
rate T <-> V: 2.710680
rate W <-> Y: 4.877884
rate W <-> V: 0.320637
rate Y <-> V: 1.203103

freq pi(A): 0.074000
freq pi(R): 0.052000
freq pi(N ): 0.045000
freq pi(D): 0.054000
freq pi(C): 0.025000
freq pi(Q): 0.034000
freq pi(E): 0.054000
freq pi(G): 0.074000
freq pi(H): 0.026000
freq pi(I): 0.068000
freq pi(L): 0.099000
freq pi(K): 0.058000
freq pi(M): 0.025000
freq pi(F): 0.047000
freq pi(P): 0.039000
freq pi(S): 0.057000
freq pi(T): 0.051000
freq pi(W): 0.013000
freq pi(Y): 0.032000
freq pi(V): 0.073000

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/BLOSUM62/RAxML_result.G
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/BLOSUM62/RAxML_log.G
