
You are using a proportion of Invariable sites estimate, although I don't
like it. The likelihood epsilon "-f e" will be automatically lowered to 0.001
to avoid unfavorable effects caused by simultaneous optimization of alpha and P-Invar


IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Found 0 invariant alignment patterns that correspond to 0 columns 
Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.001000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA+P-Invar model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA+P-Invar Model parameters will be estimated up to an accuracy of 0.0010000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: DCMUT
Fixed Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAIDCMUT -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GI -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DCMUT 



Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DCMUT/RAxML_binaryModelParameters.GI


Overall Time for Tree Evaluation 50.621092
Final GAMMA  likelihood: -39037.826256


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.960274
invar: 0.054758
Tree-Length: 170.131729
rate A <-> R: 0.235171
rate A <-> N : 0.864434
rate A <-> D: 1.053509
rate A <-> C: 0.316118
rate A <-> Q: 0.779506
rate A <-> E: 1.722035
rate A <-> G: 2.095164
rate A <-> H: 0.200301
rate A <-> I: 0.573743
rate A <-> L: 0.356873
rate A <-> K: 0.227099
rate A <-> M: 0.630311
rate A <-> F: 0.161249
rate A <-> P: 2.182803
rate A <-> S: 3.557811
rate A <-> T: 3.231605
rate A <-> W: 0.000000
rate A <-> Y: 0.214370
rate A <-> V: 1.808434
rate R <-> N : 0.287180
rate R <-> D: 0.000000
rate R <-> C: 0.204040
rate R <-> Q: 2.142429
rate R <-> E: 0.000000
rate R <-> G: 0.077086
rate R <-> H: 2.092562
rate R <-> I: 0.555490
rate R <-> L: 0.136034
rate R <-> K: 4.047995
rate R <-> M: 0.787029
rate R <-> F: 0.120213
rate R <-> P: 0.902927
rate R <-> S: 1.344838
rate R <-> T: 0.233342
rate R <-> W: 1.757340
rate R <-> Y: 0.068500
rate R <-> V: 0.211059
rate N  <-> D: 7.842464
rate N  <-> C: 0.000000
rate N  <-> Q: 0.903099
rate N  <-> E: 1.311312
rate N  <-> G: 1.216431
rate N  <-> H: 4.644993
rate N  <-> I: 0.674376
rate N  <-> L: 0.299520
rate N  <-> K: 2.764479
rate N  <-> M: 0.000000
rate N  <-> F: 0.121615
rate N  <-> P: 0.368124
rate N  <-> S: 4.290138
rate N  <-> T: 1.994701
rate N  <-> W: 0.197537
rate N  <-> Y: 0.831476
rate N  <-> V: 0.138793
rate D <-> C: 0.000000
rate D <-> Q: 1.184117
rate D <-> E: 10.000000
rate D <-> G: 1.089664
rate D <-> H: 0.762373
rate D <-> I: 0.210076
rate D <-> L: 0.000000
rate D <-> K: 0.629497
rate D <-> M: 0.000000
rate D <-> F: 0.000000
rate D <-> P: 0.117608
rate D <-> S: 0.839517
rate D <-> T: 0.580340
rate D <-> W: 0.000000
rate D <-> Y: 0.000000
rate D <-> V: 0.156573
rate C <-> Q: 0.000000
rate C <-> E: 0.000000
rate C <-> G: 0.094197
rate C <-> H: 0.248255
rate C <-> I: 0.384658
rate C <-> L: 0.000000
rate C <-> K: 0.000000
rate C <-> M: 0.000000
rate C <-> F: 0.000000
rate C <-> P: 0.164681
rate C <-> S: 1.403463
rate C <-> T: 0.142568
rate C <-> W: 0.000000
rate C <-> Y: 0.836941
rate C <-> V: 0.425580
rate Q <-> E: 6.221999
rate Q <-> G: 0.247247
rate Q <-> H: 5.278596
rate Q <-> I: 0.158397
rate Q <-> L: 0.641666
rate Q <-> K: 1.333852
rate Q <-> M: 0.990019
rate Q <-> F: 0.000000
rate Q <-> P: 1.340095
rate Q <-> S: 0.493322
rate Q <-> T: 0.461557
rate Q <-> W: 0.000000
rate Q <-> Y: 0.000000
rate Q <-> V: 0.304674
rate E <-> G: 0.712908
rate E <-> H: 0.385883
rate E <-> I: 0.535204
rate E <-> L: 0.099116
rate E <-> K: 0.728864
rate E <-> M: 0.267637
rate E <-> F: 0.000000
rate E <-> P: 0.445182
rate E <-> S: 0.697184
rate E <-> T: 0.298680
rate E <-> W: 0.000000
rate E <-> Y: 0.188536
rate E <-> V: 0.322470
rate G <-> H: 0.093779
rate G <-> I: 0.000000
rate G <-> L: 0.062794
rate G <-> K: 0.235043
rate G <-> M: 0.149598
rate G <-> F: 0.134764
rate G <-> P: 0.304823
rate G <-> S: 2.039084
rate G <-> T: 0.269270
rate G <-> W: 0.000000
rate G <-> Y: 0.000000
rate G <-> V: 0.472545
rate H <-> I: 0.067594
rate H <-> L: 0.389426
rate H <-> K: 0.237495
rate H <-> M: 0.000000
rate H <-> F: 0.417896
rate H <-> P: 0.819859
rate H <-> S: 0.310522
rate H <-> T: 0.198735
rate H <-> W: 0.237573
rate H <-> Y: 1.111105
rate H <-> V: 0.385221
rate I <-> L: 2.244939
rate I <-> K: 0.404663
rate I <-> M: 2.926360
rate I <-> F: 1.713943
rate I <-> P: 0.104623
rate I <-> S: 0.217721
rate I <-> T: 1.668975
rate I <-> W: 0.000000
rate I <-> Y: 0.329129
rate I <-> V: 7.735799
rate L <-> K: 0.158604
rate L <-> M: 4.592389
rate L <-> F: 1.374315
rate L <-> P: 0.277696
rate L <-> S: 0.150529
rate L <-> T: 0.290719
rate L <-> W: 0.405470
rate L <-> Y: 0.251629
rate L <-> V: 1.532363
rate K <-> M: 2.117667
rate K <-> F: 0.000000
rate K <-> P: 0.294520
rate K <-> S: 0.838165
rate K <-> T: 1.185916
rate K <-> W: 0.000000
rate K <-> Y: 0.116029
rate K <-> V: 0.091187
rate M <-> F: 0.809454
rate M <-> P: 0.149451
rate M <-> S: 0.544358
rate M <-> T: 0.905755
rate M <-> W: 0.000000
rate M <-> Y: 0.000000
rate M <-> V: 2.253079
rate F <-> P: 0.097032
rate F <-> S: 0.403824
rate F <-> T: 0.119992
rate F <-> W: 0.669398
rate F <-> Y: 6.104871
rate F <-> V: 0.108534
rate P <-> S: 2.131245
rate P <-> T: 0.687401
rate P <-> W: 0.000000
rate P <-> Y: 0.000000
rate P <-> V: 0.425885
rate S <-> T: 4.773761
rate S <-> W: 0.650488
rate S <-> Y: 0.295284
rate S <-> V: 0.266788
rate T <-> W: 0.000000
rate T <-> Y: 0.366890
rate T <-> V: 1.371537
rate W <-> Y: 0.533926
rate W <-> V: 0.000000
rate Y <-> V: 0.245313

freq pi(A): 0.087000
freq pi(R): 0.041000
freq pi(N ): 0.040000
freq pi(D): 0.047000
freq pi(C): 0.033000
freq pi(Q): 0.038000
freq pi(E): 0.049000
freq pi(G): 0.089000
freq pi(H): 0.034000
freq pi(I): 0.037000
freq pi(L): 0.085000
freq pi(K): 0.080000
freq pi(M): 0.015000
freq pi(F): 0.040000
freq pi(P): 0.052000
freq pi(S): 0.069000
freq pi(T): 0.059000
freq pi(W): 0.010000
freq pi(Y): 0.030000
freq pi(V): 0.065000

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DCMUT/RAxML_result.GI
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/DCMUT/RAxML_log.GI
