

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: HIVB
Fixed Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAHIVB -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n G -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/HIVB 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.280486
Subtree Equality Vectors for gap columns full tree traversal time: 1.352212
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/HIVB/RAxML_binaryModelParameters.G


Overall Time for Tree Evaluation 53.820910
Final GAMMA  likelihood: -39679.339253


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.658625
Tree-Length: 178.285712
rate A <-> R: 0.150370
rate A <-> N : 0.002445
rate A <-> D: 0.711511
rate A <-> C: 0.060517
rate A <-> Q: 0.026950
rate A <-> E: 0.724377
rate A <-> G: 1.044186
rate A <-> H: 0.041448
rate A <-> I: 0.002445
rate A <-> L: 0.105260
rate A <-> K: 0.002445
rate A <-> M: 0.009127
rate A <-> F: 0.006908
rate A <-> P: 1.037736
rate A <-> S: 1.206029
rate A <-> T: 7.784010
rate A <-> W: 0.002445
rate A <-> Y: 0.002445
rate A <-> V: 3.723364
rate R <-> N : 0.144520
rate R <-> D: 0.002445
rate R <-> C: 0.171991
rate R <-> Q: 1.673105
rate R <-> E: 0.036637
rate R <-> G: 1.786528
rate R <-> H: 4.420753
rate R <-> I: 0.331193
rate R <-> L: 0.342996
rate R <-> K: 10.000000
rate R <-> M: 1.229311
rate R <-> F: 0.002445
rate R <-> P: 0.627653
rate R <-> S: 1.701271
rate R <-> T: 1.402778
rate R <-> W: 0.484762
rate R <-> Y: 0.004850
rate R <-> V: 0.039729
rate N  <-> D: 8.636284
rate N  <-> C: 0.042085
rate N  <-> Q: 0.328632
rate N  <-> E: 0.038760
rate N  <-> G: 0.158142
rate N  <-> H: 3.738802
rate N  <-> I: 0.332795
rate N  <-> L: 0.002445
rate N  <-> K: 3.865247
rate N  <-> M: 0.002445
rate N  <-> F: 0.002445
rate N  <-> P: 0.003617
rate N  <-> S: 6.427726
rate N  <-> T: 3.367565
rate N  <-> W: 0.002445
rate N  <-> Y: 0.862675
rate N  <-> V: 0.013035
rate D <-> C: 0.002445
rate D <-> Q: 0.002445
rate D <-> E: 5.177115
rate D <-> G: 1.387804
rate D <-> H: 0.937359
rate D <-> I: 0.008645
rate D <-> L: 0.004284
rate D <-> K: 0.002445
rate D <-> M: 0.002445
rate D <-> F: 0.002445
rate D <-> P: 0.016756
rate D <-> S: 0.258303
rate D <-> T: 0.134339
rate D <-> W: 0.002445
rate D <-> Y: 0.329904
rate D <-> V: 0.512435
rate C <-> Q: 0.002445
rate C <-> E: 0.002445
rate C <-> G: 0.439057
rate C <-> H: 0.117395
rate C <-> I: 0.002445
rate C <-> L: 0.063461
rate C <-> K: 0.002445
rate C <-> M: 0.002445
rate C <-> F: 4.546773
rate C <-> P: 0.002445
rate C <-> S: 2.294934
rate C <-> T: 0.361843
rate C <-> W: 1.287418
rate C <-> Y: 3.706269
rate C <-> V: 0.205392
rate Q <-> E: 1.251932
rate Q <-> G: 0.030276
rate Q <-> H: 3.450098
rate Q <-> I: 0.002445
rate Q <-> L: 0.730836
rate Q <-> K: 3.201648
rate Q <-> M: 0.148497
rate Q <-> F: 0.002445
rate Q <-> P: 2.186851
rate Q <-> S: 0.056876
rate Q <-> T: 0.119114
rate Q <-> W: 0.013035
rate Q <-> Y: 0.055273
rate Q <-> V: 0.010228
rate E <-> G: 1.920660
rate E <-> H: 0.058553
rate E <-> I: 0.002978
rate E <-> L: 0.002445
rate E <-> K: 2.256636
rate E <-> M: 0.085960
rate E <-> F: 0.002445
rate E <-> P: 0.005879
rate E <-> S: 0.002445
rate E <-> T: 0.141699
rate E <-> W: 0.002445
rate E <-> Y: 0.038760
rate E <-> V: 0.502919
rate G <-> H: 0.002445
rate G <-> I: 0.002445
rate G <-> L: 0.002445
rate G <-> K: 0.255112
rate G <-> M: 0.002445
rate G <-> F: 0.142573
rate G <-> P: 0.002445
rate G <-> S: 2.142010
rate G <-> T: 0.180741
rate G <-> W: 0.594983
rate G <-> Y: 0.002445
rate G <-> V: 0.466090
rate H <-> I: 0.050421
rate H <-> L: 0.851692
rate H <-> K: 0.002445
rate H <-> M: 0.002445
rate H <-> F: 0.071178
rate H <-> P: 1.199599
rate H <-> S: 0.187162
rate H <-> T: 0.347968
rate H <-> W: 0.033994
rate H <-> Y: 9.141467
rate H <-> V: 0.002445
rate I <-> L: 2.913834
rate I <-> K: 0.157613
rate I <-> M: 5.479951
rate I <-> F: 1.661790
rate I <-> P: 0.020078
rate I <-> S: 0.595614
rate I <-> T: 4.211330
rate I <-> W: 0.002445
rate I <-> Y: 0.072454
rate I <-> V: 8.674279
rate L <-> K: 0.039853
rate L <-> M: 2.601276
rate L <-> F: 4.168626
rate L <-> P: 1.015927
rate L <-> S: 0.453622
rate L <-> T: 0.021402
rate L <-> W: 0.366182
rate L <-> Y: 0.054761
rate L <-> V: 0.689663
rate K <-> M: 0.627120
rate K <-> F: 0.016756
rate K <-> P: 0.015348
rate K <-> S: 0.246509
rate K <-> T: 2.284313
rate K <-> W: 0.002445
rate K <-> Y: 0.002445
rate K <-> V: 0.129990
rate M <-> F: 0.091944
rate M <-> P: 0.002445
rate M <-> S: 0.002445
rate M <-> T: 2.415775
rate M <-> W: 0.043559
rate M <-> Y: 0.002445
rate M <-> V: 3.351198
rate F <-> P: 0.002445
rate F <-> S: 0.467712
rate F <-> T: 0.006908
rate F <-> W: 0.405547
rate F <-> Y: 7.501222
rate F <-> V: 0.353679
rate P <-> S: 2.629643
rate P <-> T: 0.984924
rate P <-> W: 0.021736
rate P <-> Y: 0.014884
rate P <-> V: 0.002445
rate S <-> T: 4.367271
rate S <-> W: 0.012163
rate S <-> Y: 0.316882
rate S <-> V: 0.036637
rate T <-> W: 0.002445
rate T <-> Y: 0.051664
rate T <-> V: 0.346810
rate W <-> Y: 0.626024
rate W <-> V: 0.002445
rate Y <-> V: 0.020078

freq pi(A): 0.060000
freq pi(R): 0.066000
freq pi(N ): 0.044000
freq pi(D): 0.042000
freq pi(C): 0.020000
freq pi(Q): 0.054000
freq pi(E): 0.071000
freq pi(G): 0.072000
freq pi(H): 0.022000
freq pi(I): 0.070000
freq pi(L): 0.099000
freq pi(K): 0.057000
freq pi(M): 0.020000
freq pi(F): 0.029000
freq pi(P): 0.046000
freq pi(S): 0.051000
freq pi(T): 0.054000
freq pi(W): 0.033000
freq pi(Y): 0.028000
freq pi(V): 0.062000

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/HIVB/RAxML_result.G
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/HIVB/RAxML_log.G
