

IMPORTANT WARNING: Sequences Aq1 and Aq36 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq34 are exactly identical


IMPORTANT WARNING: Sequences Aq33 and Aq35 are exactly identical


IMPORTANT WARNING: Sequences Dm25 and Dm80 are exactly identical


IMPORTANT WARNING: Sequences Dm36 and Dm72 are exactly identical


IMPORTANT WARNING: Sequences Dm37 and Dm73 are exactly identical


IMPORTANT WARNING: Sequences Dm38 and Dm74 are exactly identical


IMPORTANT WARNING: Sequences Dm39 and Dm75 are exactly identical


IMPORTANT WARNING: Sequences Hs1 and Hs114 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs103 are exactly identical


IMPORTANT WARNING: Sequences Hs102 and Hs64 are exactly identical


IMPORTANT WARNING: Sequences Hs104 and Hs187 are exactly identical


IMPORTANT WARNING: Sequences Hs105 and Hs184 are exactly identical


IMPORTANT WARNING: Sequences Hs106 and Hs185 are exactly identical


IMPORTANT WARNING: Sequences Hs108 and Hs183 are exactly identical


IMPORTANT WARNING: Sequences Hs115 and Hs2 are exactly identical


IMPORTANT WARNING: Sequences Hs116 and Hs3 are exactly identical


IMPORTANT WARNING: Sequences Hs117 and Hs4 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs205 are exactly identical


IMPORTANT WARNING: Sequences Hs118 and Hs223 are exactly identical


IMPORTANT WARNING: Sequences Hs119 and Hs224 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs124 are exactly identical


IMPORTANT WARNING: Sequences Hs121 and Hs126 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs123 are exactly identical


IMPORTANT WARNING: Sequences Hs122 and Hs125 are exactly identical


IMPORTANT WARNING: Sequences Hs132 and Hs217 are exactly identical


IMPORTANT WARNING: Sequences Hs133 and Hs219 are exactly identical


IMPORTANT WARNING: Sequences Hs134 and Hs220 are exactly identical


IMPORTANT WARNING: Sequences Hs135 and Hs221 are exactly identical


IMPORTANT WARNING: Sequences Hs136 and Hs222 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs140 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs143 are exactly identical


IMPORTANT WARNING: Sequences Hs137 and Hs146 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs141 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs144 are exactly identical


IMPORTANT WARNING: Sequences Hs138 and Hs147 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs142 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs145 are exactly identical


IMPORTANT WARNING: Sequences Hs139 and Hs148 are exactly identical


IMPORTANT WARNING: Sequences Hs149 and Hs274 are exactly identical


IMPORTANT WARNING: Sequences Hs150 and Hs275 are exactly identical


IMPORTANT WARNING: Sequences Hs151 and Hs276 are exactly identical


IMPORTANT WARNING: Sequences Hs152 and Hs32 are exactly identical


IMPORTANT WARNING: Sequences Hs160 and Hs267 are exactly identical


IMPORTANT WARNING: Sequences Hs161 and Hs268 are exactly identical


IMPORTANT WARNING: Sequences Hs17 and Hs212 are exactly identical


IMPORTANT WARNING: Sequences Hs172 and Hs255 are exactly identical


IMPORTANT WARNING: Sequences Hs173 and Hs256 are exactly identical


IMPORTANT WARNING: Sequences Hs177 and Hs36 are exactly identical


IMPORTANT WARNING: Sequences Hs18 and Hs213 are exactly identical


IMPORTANT WARNING: Sequences Hs188 and Hs286 are exactly identical


IMPORTANT WARNING: Sequences Hs189 and Hs287 are exactly identical


IMPORTANT WARNING: Sequences Hs19 and Hs214 are exactly identical


IMPORTANT WARNING: Sequences Hs190 and Hs288 are exactly identical


IMPORTANT WARNING: Sequences Hs191 and Hs289 are exactly identical


IMPORTANT WARNING: Sequences Hs192 and Hs290 are exactly identical


IMPORTANT WARNING: Sequences Hs193 and Hs5 are exactly identical


IMPORTANT WARNING: Sequences Hs194 and Hs6 are exactly identical


IMPORTANT WARNING: Sequences Hs195 and Hs7 are exactly identical


IMPORTANT WARNING: Sequences Hs196 and Hs72 are exactly identical


IMPORTANT WARNING: Sequences Hs197 and Hs73 are exactly identical


IMPORTANT WARNING: Sequences Hs209 and Hs252 are exactly identical


IMPORTANT WARNING: Sequences Hs210 and Hs253 are exactly identical


IMPORTANT WARNING: Sequences Hs211 and Hs254 are exactly identical


IMPORTANT WARNING: Sequences Hs215 and Hs216 are exactly identical


IMPORTANT WARNING: Sequences Hs228 and Hs266 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs239 are exactly identical


IMPORTANT WARNING: Sequences Hs232 and Hs243 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs236 are exactly identical


IMPORTANT WARNING: Sequences Hs233 and Hs240 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs237 are exactly identical


IMPORTANT WARNING: Sequences Hs234 and Hs241 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs238 are exactly identical


IMPORTANT WARNING: Sequences Hs235 and Hs242 are exactly identical


IMPORTANT WARNING: Sequences Hs24 and Hs26 are exactly identical


IMPORTANT WARNING: Sequences Hs25 and Hs27 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs260 are exactly identical


IMPORTANT WARNING: Sequences Hs257 and Hs264 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs261 are exactly identical


IMPORTANT WARNING: Sequences Hs258 and Hs262 are exactly identical


IMPORTANT WARNING: Sequences Hs259 and Hs263 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs60 are exactly identical


IMPORTANT WARNING: Sequences Hs282 and Hs61 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs40 are exactly identical


IMPORTANT WARNING: Sequences Hs38 and Hs42 are exactly identical


IMPORTANT WARNING: Sequences Hs39 and Hs41 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs47 are exactly identical


IMPORTANT WARNING: Sequences Hs45 and Hs49 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs48 are exactly identical


IMPORTANT WARNING: Sequences Hs46 and Hs50 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs74 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs78 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs82 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs86 are exactly identical


IMPORTANT WARNING: Sequences Hs51 and Hs90 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs75 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs79 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs83 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs87 are exactly identical


IMPORTANT WARNING: Sequences Hs52 and Hs91 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs76 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs80 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs84 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs88 are exactly identical


IMPORTANT WARNING: Sequences Hs53 and Hs92 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs77 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs81 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs85 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs89 are exactly identical


IMPORTANT WARNING: Sequences Hs54 and Hs93 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs57 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs58 are exactly identical


IMPORTANT WARNING: Sequences Hs56 and Hs59 are exactly identical


IMPORTANT WARNING: Sequences Hs62 and Hs63 are exactly identical


IMPORTANT WARNING: Sequences Hs65 and Hs68 are exactly identical


IMPORTANT WARNING: Sequences Hs66 and Hs69 are exactly identical


IMPORTANT WARNING: Sequences Hs67 and Hs70 are exactly identical


IMPORTANT WARNING: Sequences Hs94 and Hs97 are exactly identical


IMPORTANT WARNING: Sequences Hs95 and Hs98 are exactly identical


IMPORTANT WARNING: Sequences Hs96 and Hs99 are exactly identical


IMPORTANT WARNING: Sequences Nv30 and Nv73 are exactly identical


IMPORTANT WARNING: Sequences Nv5 and Nv61 are exactly identical


IMPORTANT WARNING: Sequences Nv54 and Nv67 are exactly identical


IMPORTANT WARNING: Sequences Nv59 and Nv6 are exactly identical

IMPORTANT WARNING
Found 124 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.

An alignment file with sequence duplicates removed has already
been printed to file example4.phy.reduced


This is RAxML version 7.2.8 released by Alexandros Stamatakis in October 2010.

With greatly appreciated code contributions by:
Andre Aberer (TUM)
Simon Berger (TUM)
John Cazes (TACC)
Michael Ott (TUM)
Nick Pattengale (UNM)
Wayne Pfeiffer (SDSC)
Akifumi S. Tanabe (Univ. Tsukuba)


Alignment has 54 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 5.42%

RAxML Model Optimization up to an accuracy of 0.100000 log likelihood units

Using 1 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 54
Name: No Name Provided
DataType: AA
Substitution Matrix: PMB
Empirical Base Frequencies:




RAxML was called as follows:

/home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/raxmlHPC-HYBRID -f e -m PROTGAMMAPMBF -s example4.phy -t /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/STARTING_TREE/RAxML_parsimonyTree.ST.tre -n GF -w /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/PMB 


Testing which likelihood implementation to use
Standard Implementation full tree traversal time: 1.221278
Subtree Equality Vectors for gap columns full tree traversal time: 1.298758
... using standard implementation


Model parameters (binary file format) written to: /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/PMB/RAxML_binaryModelParameters.GF


Overall Time for Tree Evaluation 47.859446
Final GAMMA  likelihood: -38999.701757


Model Parameters of Partition 0, Name: No Name Provided, Type of Data: AA
alpha: 0.778701
Tree-Length: 123.955658
rate A <-> R: 0.843451
rate A <-> N : 0.736800
rate A <-> D: 0.577923
rate A <-> C: 1.331343
rate A <-> Q: 1.389224
rate A <-> E: 1.307462
rate A <-> G: 1.984264
rate A <-> H: 0.725786
rate A <-> I: 0.580536
rate A <-> L: 1.005155
rate A <-> K: 1.039636
rate A <-> M: 1.932732
rate A <-> F: 0.682474
rate A <-> P: 1.551442
rate A <-> S: 4.313882
rate A <-> T: 2.188503
rate A <-> W: 0.437486
rate A <-> Y: 0.716194
rate A <-> V: 2.577914
rate R <-> N : 1.485816
rate R <-> D: 0.756562
rate R <-> C: 0.392923
rate R <-> Q: 3.708508
rate R <-> E: 1.501690
rate R <-> G: 0.654485
rate R <-> H: 1.820774
rate R <-> I: 0.449401
rate R <-> L: 0.650650
rate R <-> K: 6.193436
rate R <-> M: 1.016474
rate R <-> F: 0.379164
rate R <-> P: 0.819431
rate R <-> S: 1.137284
rate R <-> T: 1.118574
rate R <-> W: 0.773203
rate R <-> Y: 0.785475
rate R <-> V: 0.485681
rate N  <-> D: 4.465160
rate N  <-> C: 0.737059
rate N  <-> Q: 2.873693
rate N  <-> E: 1.596739
rate N  <-> G: 1.717969
rate N  <-> H: 2.852803
rate N  <-> I: 0.532401
rate N  <-> L: 0.512439
rate N  <-> K: 2.546082
rate N  <-> M: 0.921986
rate N  <-> F: 0.531307
rate N  <-> P: 0.889059
rate N  <-> S: 3.214601
rate N  <-> T: 2.278157
rate N  <-> W: 0.527825
rate N  <-> Y: 0.899704
rate N  <-> V: 0.592817
rate D <-> C: 0.308582
rate D <-> Q: 2.106838
rate D <-> E: 5.498077
rate D <-> G: 0.918420
rate D <-> H: 1.048820
rate D <-> I: 0.333353
rate D <-> L: 0.336289
rate D <-> K: 1.392238
rate D <-> M: 0.427267
rate D <-> F: 0.273661
rate D <-> P: 0.969193
rate D <-> S: 1.800493
rate D <-> T: 1.242351
rate D <-> W: 0.452961
rate D <-> Y: 0.545085
rate D <-> V: 0.344453
rate C <-> Q: 0.306348
rate C <-> E: 0.113800
rate C <-> G: 0.396195
rate C <-> H: 0.514250
rate C <-> I: 0.521752
rate C <-> L: 0.563298
rate C <-> K: 0.342585
rate C <-> M: 0.772999
rate C <-> F: 0.836216
rate C <-> P: 0.248263
rate C <-> S: 1.247941
rate C <-> T: 1.058771
rate C <-> W: 0.556893
rate C <-> Y: 0.695085
rate C <-> V: 1.248204
rate Q <-> E: 5.197786
rate Q <-> G: 0.745727
rate Q <-> H: 2.264427
rate Q <-> I: 0.393934
rate Q <-> L: 0.781969
rate Q <-> K: 4.400149
rate Q <-> M: 2.583335
rate Q <-> F: 0.507376
rate Q <-> P: 1.062275
rate Q <-> S: 1.684753
rate Q <-> T: 1.650208
rate Q <-> W: 0.900167
rate Q <-> Y: 0.910896
rate Q <-> V: 0.792734
rate E <-> G: 0.579564
rate E <-> H: 1.096921
rate E <-> I: 0.380137
rate E <-> L: 0.400841
rate E <-> K: 3.018916
rate E <-> M: 0.664485
rate E <-> F: 0.280096
rate E <-> P: 0.992884
rate E <-> S: 1.506362
rate E <-> T: 1.186586
rate E <-> W: 0.326459
rate E <-> Y: 0.633779
rate E <-> V: 0.659321
rate G <-> H: 0.595207
rate G <-> I: 0.225170
rate G <-> L: 0.324705
rate G <-> K: 0.725998
rate G <-> M: 0.581484
rate G <-> F: 0.442382
rate G <-> P: 0.735061
rate G <-> S: 1.752042
rate G <-> T: 0.677496
rate G <-> W: 0.473270
rate G <-> Y: 0.355785
rate G <-> V: 0.393239
rate H <-> I: 0.356359
rate H <-> L: 0.454818
rate H <-> K: 1.231927
rate H <-> M: 0.475991
rate H <-> F: 0.720039
rate H <-> P: 0.569875
rate H <-> S: 0.999610
rate H <-> T: 1.037629
rate H <-> W: 0.905144
rate H <-> Y: 2.762727
rate H <-> V: 0.382107
rate I <-> L: 5.201255
rate I <-> K: 0.468318
rate I <-> M: 4.570994
rate I <-> F: 1.868429
rate I <-> P: 0.457632
rate I <-> S: 0.663071
rate I <-> T: 1.392180
rate I <-> W: 0.645101
rate I <-> Y: 0.712954
rate I <-> V: 10.000000
rate L <-> K: 0.622297
rate L <-> M: 6.250743
rate L <-> F: 2.989755
rate L <-> P: 0.537404
rate L <-> S: 0.502915
rate L <-> T: 0.974444
rate L <-> W: 0.993150
rate L <-> Y: 1.013421
rate L <-> V: 2.640426
rate K <-> M: 0.826082
rate K <-> F: 0.336753
rate K <-> P: 1.294647
rate K <-> S: 1.542772
rate K <-> T: 1.612824
rate K <-> W: 0.541573
rate K <-> Y: 0.830816
rate K <-> V: 0.657501
rate M <-> F: 2.882645
rate M <-> P: 0.421731
rate M <-> S: 1.181405
rate M <-> T: 1.938684
rate M <-> W: 0.960159
rate M <-> Y: 1.165264
rate M <-> V: 2.170938
rate F <-> P: 0.601221
rate F <-> S: 0.766271
rate F <-> T: 0.898306
rate F <-> W: 4.117556
rate F <-> Y: 7.365851
rate F <-> V: 1.229377
rate P <-> S: 1.521573
rate P <-> T: 0.975801
rate P <-> W: 0.624619
rate P <-> Y: 0.541996
rate P <-> V: 0.688927
rate S <-> T: 5.559290
rate S <-> W: 0.620202
rate S <-> Y: 0.741986
rate S <-> V: 0.634161
rate T <-> W: 0.479487
rate T <-> Y: 0.654209
rate T <-> V: 2.373736
rate W <-> Y: 3.744005
rate W <-> V: 0.536776
rate Y <-> V: 0.895682

freq pi(A): 0.054853
freq pi(R): 0.046897
freq pi(N ): 0.032881
freq pi(D): 0.049507
freq pi(C): 0.131460
freq pi(Q): 0.034963
freq pi(E): 0.060758
freq pi(G): 0.071417
freq pi(H): 0.049166
freq pi(I): 0.037791
freq pi(L): 0.063710
freq pi(K): 0.070547
freq pi(M): 0.015135
freq pi(F): 0.055008
freq pi(P): 0.033005
freq pi(S): 0.045281
freq pi(T): 0.038599
freq pi(W): 0.011561
freq pi(Y): 0.046804
freq pi(V): 0.050657

Final tree written to:                 /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/PMB/RAxML_result.GF
Execution Log File written to:         /home/kochbj/scripts/01-Utilities/RAXModelerwithDecision/example4/RAxML_files_16_32_19_7_4_2011/PMB/RAxML_log.GF
